@echo off
echo Restarting backend server...
cd backend
echo Stopping any running processes...
taskkill /F /IM node.exe 2>nul
echo Generating Prisma client...
node node_modules\prisma\build\index.js generate --schema prisma\schema.prisma
echo Starting backend server...
npm run dev
pause
